version: '2.7'

services:
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build:
      context: ./requirements/nginx/
    image: nginx
    ports:
      - "443:443"
    networks:
      - dockernetwork
    volumes:
      - wp_volume:/var/www/wordpress
    restart: always

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    env_file: .env
    build:
      context: ./requirements/wordpress/
    image: wordpress
    networks:
      - dockernetwork
    volumes:
      - wp_volume:/var/www/wordpress
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
      args:
        DB_NAME: ${MYSQL_NAME}
        DB_USER: ${MYSQL_USER}
        DB_PASS: ${MYSQL_PASSWORD}
        DB_ROOT_PASS: ${MYSQL_ROOT_PASSWORD}
    image: mariadb
    # env_file: .env
    networks:
      - dockernetwork
    volumes:
      - db_volume:/var/lib/mysql
    restart: always

volumes:
  wp_volume:
    name: wp_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wp
  db_volume:
    name: db_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/db

networks:
  dockernetwork:
    name: docker_net
    