version: '3'

services:
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    images: nginx
    build:
      context: ./requirements/nginx/
    ports:
      - "443:443"
    networks:
      - docker_net
    volumes:
      - wp_volume:/var/www/html
    restart: always

  wordpress
    depends_on:
      - mariadb
    container_name: wordpress
    images: wordpress
    build:
      context: ./requirements/wordpress/
    networks:
      - docker_net
    volumes:
      - wp_volume:/var/www/html
    restart: always

  mariadb
    container_name: mariadb
    images: mariadb
    build:
      context: ./requirements/mariadb/
    networks:
      - docker_net
    # volumes:
    #   - wp_volume:/var/www/html
    restart: always
  

volumes:
  wp_volume:
    name: wp_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wp

networks:
  dockernetwork:
    name: docker_net
    driver: bridge
    