-- CREATE DATABASE wordpress;
-- CREATE USER 'sfearow'@'%' IDENTIFIED BY '222';
-- GRANT ALL PRIVILEGES ON wordpress.* TO 'sfearow'@'%';
-- FLUSH PRIVILEGES;

-- ALTER USER 'root'@'localhost' IDENTIFIED BY '123';
CREATE DATABASE REPLACE_DB_NAME;
CREATE USER 'REPLACE_USER'@'%' IDENTIFIED BY 'REPLACE_PASSWORD';
GRANT ALL PRIVILEGES ON REPLACE_DB_NAME.* TO 'REPLACE_USER'@'%';
FLUSH PRIVILEGES;

ALTER USER 'root'@'localhost' IDENTIFIED BY 'REPLACE_ROOT_PASS';