CREATE DATABASE REPLACE_DB_NAME;
CREATE USER 'REPLACE_USER'@'%' IDENTIFIED BY 'REPLACE_PASSWORD';
GRANT ALL PRIVILEGES ON REPLACE_DB_NAME.* TO 'REPLACE_USER'@'%';
FLUSH PRIVILEGES;

ALTER USER 'root'@'localhost' IDENTIFIED BY 'REPLACE_ROOT_PASS';
